#Messages for guilds plugin
msg:
    guild:
        deleted: "&aYou have deleted &e%pstring%"
        created: "&aYou have created &e%pstring%"
        sentinvite: "&aInvite sent to &e%rstring%"
        joined: "&aYou have joined &e%pstring%"
        receivedinvite: "&aYou have received an invite from &e%rstring%"
        leftguild: "&aYou have left &e%pstring%"
        kickedplayer: "&aYou have kicked &e%rstring%"
        reloaded: "&bGuilds has been reloaded"
        promote: "&aYou have promoted &e%pstring% &ato &e%rstring%"
        demote: "&aYou have demoted &e%pstring% &ato %e%rstring%"
        error:
            notinguild: "&cNot in a guild"
            nothighrank: "&cYou are not high enough rank to do this"
            vnotinguild: "&c%rstring% is not in a guild"
            nametaken: "&cThat name is taken"
            nametoolong: "&cName too long"
            ranktoolow: "&cRank too low"
            alreadyinguild: "&cAlready in guild"
            doesnotexist: "&e%rstring% &cdoes not exist"
            playerhasinvite: "&e%rstring% &calready has an invite"
            playeralreadyinguild: "&e%receiver% &cis already in a guild"
            inviteself: "&cYou cannot invite yourself"
            noinvite: "&cYou do not have an invite"
            leaveasleader: "&cYou cannot leave as the leader"
            kickself: "&cYou cannot kick yourself"
            promoteself: "&cYou cannot promote yourself"
            demoteself: "&cYou cannot demote yourself"
            lowdemote: "&cYou cannot demote %pstring% any further"
 
#Error messages (general errors
error:
    nopermission: "&cNo perm"
    playeronly: "&cPlayer only"
    invalidargs: "&cInvalid arguments"
    playernotonline: "&e%rstring%&c is not online"
    nocommand: "&cInvalid guild command"
    noplayer: "&c%rstring% is not a real player"

#Guild default values
default:
    guild:
        lives: 10
        namelength: 14
    invites:
        duration: 120