#Messages for guilds plugin
msg:
    guild:
        deleted: "&9Guilds> &7You have deleted &e%pstring%"
        created: "&9Guilds> &7You have created &e%pstring%"
        sentinvite: "&9Guilds> &7Invite sent to &e%rstring%"
        joined: "&9Guilds> &7You have joined &e%pstring%"
        receivedinvite: "&9Guilds> &7You have received an invite from &e%rstring%"
        leftguild: "&9Guilds> &7You have left &e%pstring%"
        kickedplayer: "&9Guilds> &7You have kicked &e%rstring%"
        reloaded: "&9Guilds> &7Guilds has been reloaded"
        promote: "&9Guilds> &7You have promoted &9%pstring% &7to &9%rstring%"
        demote: "&9Guilds> &7You have demoted &9%pstring% &7to &9%rstring%"
        claimed: "&9Guilds> &7You have claimed this chunk"
        unclaimed: "&9Guilds> &7You have unclaimed this chunk"
        unclaimall: "&9Guilds> &7You have unclaimed all your guild's chunks"
        enterclaim: "&9Guilds> &7You have entered land owned by &9%rstring%"
        sethome: "&9Guilds> &7You have set your home to &9(%pstring%)"
        tpstart: "&9Guilds> &7You have started to teleport, do not move"
        error:
            invalidpage: "&9Guilds> &7That is not a valid page number"
            notinguild: "&9Guilds> &7Not in a guild"
            chunknotclaimed: "&9Guilds> &7Nobody owns this chunk!"
            chunktaken: "&9Guilds> &7This chunk is already claimed"
            vnotinguild: "&9Guilds> &7'%rstring%' is not in a guild"
            nametaken: "&9Guilds> &7That name is taken"
            nametoolong: "&9Guilds> &7That guild name is too long"
            ranktoolow: "&9Guilds> &7Rank too low"
            alreadyinguild: "&9Guilds> &7Already in guild"
            doesnotexist: "&9Guilds> &7'%rstring%' &cdoes not exist"
            playerhasinvite: "&9Guilds> &9%rstring% &7already has an invite"
            playeralreadyinguild: "&9Guilds> &9%receiver% &7is already in a guild"
            inviteself: "&&9Guilds> &7You cannot invite yourself"
            noinvite: "&9Guilds> &7You do not have an invite"
            leaveasleader: "&9Guilds> &7You cannot leave as the leader"
            kickself: "&9Guilds> &7You cannot kick yourself"
            promoteself: "&9Guilds> &7You cannot promote yourself"
            demoteself: "&9Guilds> &7You cannot demote yourself"
            lowdemote: "&9Guilds> &7You cannot demote %pstring% any further"
            bordering: "&9Guilds> &7You cannot claim next to territory owned by %rstring%"
            bannedguildname: "&9Guilds> &7You cannot use that guild name"
            noguilds: "&9Guilds> &7There are no guilds"
            maxplayersinguild: "&9Guilds> &7You have met the max amount of players in your guild"
            maxchunksclaimed: "&9Guilds> &7You have claimed the max amount of chunks"
            cannotsethome: "&9Guilds> &7You can only set your home in chunks you own"
            nohome: "&9Guilds> &7Your guild does not have a set home"
            alreadyteleporting: "&9Guilds> &7You are already teleporting!"
            chunkclaimedrecently: "&9Guilds> &7This chunk has been claimed recently!"
#Error messages (general errors
error:
    nopermission: "&9Error> &7You do not have permission to execute this command"
    playeronly: "&9Error> &7Only players may use this command"
    invalidargs: "&9Error> &7Invalid arguments see '/guild help' for more info"
    playernotonline: "&9Error> &7'%rstring%'&7 is not online"
    nocommand: "&9Error> &7Invalid guild command"
    noplayer: "&9Error> &7'%rstring%' is not a real player"

#Guild default values
default:
    guild:
        chatformat: true
        guildprefix: [%guild%]
        lives: 10
        namelength: 14
        raidtime: 100
        maxchunks: 5
        maxplayers: 10
        bannednames: Poop,Loser,DummyHead
    invites:
        duration: 120
    lives:
        interval: 600
        increment: 1
        max: 20
        