#Messages for guilds plugin
msg:
    guild:
        deleted: "&aYou have deleted &e%pstring%"
        created: "&aYou have created &e%pstring%"
        sentinvite: "&aInvite sent to &e%rstring%"
        joined: "&aYou have joined &e%pstring%"
        receivedinvite: "&aYou have received an invite from &e%rstring%"
        leftguild: "&aYou have left &e%pstring%"
        kickedplayer: "&aYou have kicked &e%rstring%"
        reloaded: "&bGuilds has been reloaded"
        promote: "&aYou have promoted &e%pstring% &ato &e%rstring%"
        demote: "&aYou have demoted &e%pstring% &ato %e%rstring%"
        claimed: "&aYou have claimed this chunk"
        unclaimed: "&aYou have unclaimed this chunk"
        unclaimall: "&aYou have unclaimed all your guild's chunks"
        enterclaim: "&aYou have entered land owned by %rstring%"
        sethome: "&aYou have set your home to &b(%pstring%)"
        tpstart: "&aYou have started to teleport, do not move"
        error:
            invalidpage: "&cThat is not a valid page number"
            notinguild: "&cNot in a guild"
            chunknotclaimed: "&cNobody owns this chunk!"
            chunktaken: "&cThis chunk is already claimed"
            vnotinguild: "&c%rstring% is not in a guild"
            nametaken: "&cThat name is taken"
            nametoolong: "&cName too long"
            ranktoolow: "&cRank too low"
            alreadyinguild: "&cAlready in guild"
            doesnotexist: "&e%rstring% &cdoes not exist"
            playerhasinvite: "&e%rstring% &calready has an invite"
            playeralreadyinguild: "&e%receiver% &cis already in a guild"
            inviteself: "&cYou cannot invite yourself"
            noinvite: "&cYou do not have an invite"
            leaveasleader: "&cYou cannot leave as the leader"
            kickself: "&cYou cannot kick yourself"
            promoteself: "&cYou cannot promote yourself"
            demoteself: "&cYou cannot demote yourself"
            lowdemote: "&cYou cannot demote %pstring% any further"
            bordering: "&cYou cannot claim next to territory owned by %rstring%"
            bannedguildname: "&cYou cannot use that guild name"
            noguilds: "&cThere are no guilds"
            maxplayersinguild: "&cYou have met the max amount of players in your guild"
            maxchunksclaimed: "&cYou have claimed the max amount of chunks"
            cannotsethome: "&cYou can only set your home in chunks you own"
            nohome: "&cYour guild does not have a set home"
            alreadyteleporting: "&cYou are already teleporting!"
            chunkclaimedrecently: "&cThis chunk has been claimed recently!"
#Error messages (general errors
error:
    nopermission: "&cNo perm"
    playeronly: "&cPlayer only"
    invalidargs: "&cInvalid arguments"
    playernotonline: "&e%rstring%&c is not online"
    nocommand: "&cInvalid guild command"
    noplayer: "&c%rstring% is not a real player"

#Guild default values
default:
    guild:
        lives: 10
        namelength: 14
        raidtime: 100
        maxchunks: 5
        maxplayers: 10
        bannednames: Poop,Loser,DummyHead
    invites:
        duration: 120
    lives:
        interval: 600
        increment: 1
        max: 20
        